### ISSUE TITLE
🐛 由插件发送到QQ的消息均被视为主动消息，导致了QQ机器人每天发送消息存在上限

### ISSUE THREAD

**Issue by CMBill** [GithubCin/gscore-adapter#2]
官方QQ机器人平台将机器人主动发送的消息和被动接收后回复的消息区分开，并对机器人每天发送的主动消息数量进行了严格的限制。而GSCore经由本插件发送出的消息似乎都被视为了主动消息，即使它是为了回复接收的消息而发的。如果机器人每天主动消息达到上限后便会有如下的报错：

```log
2024-01-05 15:46:28 [I] gscore-adapter 与[gsuid-core]成功连接! Bot_ID: koishi
2024-01-05 15:46:38 [I] gscore-adapter Element { type: 'text', attrs: { content: 'core刷新插件列表' }, children: [] } 0 [ Element { type: 'text', attrs: { content: 'core刷新插件列表' }, children: [] } ]
2024-01-05 15:46:38 [I] gscore-adapter Session { id: 13, event: { selfId: 'selfId', platform: 'qqguild', timestamp: 1704440796000, _type: 'qq', _data: { op: 0, s: 3, t: 'DIRECT_MESSAGE_CREATE', id: 'DIRECT_MESSAGE_CREATE:id', d: { author: { avatar: 'avatar', id: 'userid', username: 'username' }, channel_id: 'channel_id', content: 'core刷新插件列表', direct_message: true, guild_id: 'guild_id', id: 'id', member: { joined_at: '2024-01-03T10:24:56+08:00' }, seq: 121, seq_in_channel: '121', src_guild_id: 'src_guild_id', timestamp: '2024-01-05T15:46:36+08:00' } }, type: 'message-created', message: { messageId: 'messageId', id: 'id', content: 'core刷新插件列表', elements: [ Element { type: 'text', attrs: { content: 'core刷新插件列表' }, children: [] } ] }, user: { id: 'id', name: 'name', isBot: undefined, avatar: 'avatar' }, guild: { id: 'guildid' }, channel: { id: 'channelid', type: 1 } }, locales: [], user: undefined, channel: undefined, guild: undefined, permissions: [], scope: undefined, response: undefined, _stripped: { hasAt: false, content: 'core刷新插件列表', appel: false, atSelf: false, prefix: '' }, _queuedTasks: [], _queuedTimeout: undefined }
2024-01-05 15:46:39 [I] gscore-adapter {"bot_id":"qqguild","bot_self_id":"bot_self_id","msg_id":"msg_id","target_type":"channel","target_id":"target_id","content":[{"type":"text","data":"刷新成功! 刷新插件!"},{"type":"group","data":"data"}]}
2024-01-05 15:46:39 [I] gscore-adapter { bot_id: 'qqguild', bot_self_id: 'bot_self_id', msg_id: 'msg_id', target_type: 'channel', target_id: 'target_id', content: [ { type: 'text', data: '刷新成功! 刷新插件!' }, { type: 'group', data: 'data' } ] }
2024-01-05 15:46:39 [E] gscore-adapter Unknown message type: group
2024-01-05 15:46:39 [I] gscore-adapter [ Element { type: 'text', attrs: { content: '刷新成功! 刷新插件!' }, children: [] } ]
2024-01-05 15:46:39 [E] qq AxiosError: Request failed with status code 500
                            at settle (/home/bill/bots/koishi/data/instances/default/node_modules/axios/dist/node/axios.cjs:1967:12)
                            at IncomingMessage.handleStreamEnd (/home/bill/bots/koishi/data/instances/default/node_modules/axios/dist/node/axios.cjs:3062:11)
                            at IncomingMessage.emit (node:events:523:35)
                            at endReadableNT (node:internal/streams/readable:1367:12)
                            at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-01-05 15:46:39 [E] qq AxiosError: Request failed with status code 500
                            at request (/home/bill/bots/koishi/data/instances/default/node_modules/cordis-axios/lib/index.js:153:21)
                            at http (/home/bill/bots/koishi/data/instances/default/node_modules/cordis-axios/lib/index.js:172:30)
                            at _Quester.post (/home/bill/bots/koishi/data/instances/default/node_modules/cordis-axios/lib/index.js:220:16)
                            at _QQGuildMessageEncoder.flush (/home/bill/bots/koishi/data/instances/default/node_modules/@satorijs/adapter-qq/lib/index.js:806:33)
                            at _QQGuildMessageEncoder.send (/home/bill/bots/koishi/data/instances/default/node_modules/@satorijs/core/lib/index.cjs:578:16)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _QQGuildBot.sendMessage (/home/bill/bots/koishi/data/instances/default/node_modules/@satorijs/core/lib/index.cjs:339:22)
2024-01-05 15:46:39 [E] qq [response] { code: 304049, message: 'push dm message reach limit' }
2024-01-05 15:46:39 [W] app TypeError: Cannot read properties of undefined (reading 'id')
                            at _QQGuildMessageEncoder.flush (/home/bill/bots/koishi/data/instances/default/node_modules/@satorijs/adapter-qq/lib/index.js:837:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _QQGuildMessageEncoder.send (/home/bill/bots/koishi/data/instances/default/node_modules/@satorijs/core/lib/index.cjs:578:5)
                            at async _QQGuildBot.sendMessage (/home/bill/bots/koishi/data/instances/default/node_modules/@satorijs/core/lib/index.cjs:339:22)
```

不知道有没有什么解决办法，腾讯的限制太蛋疼了（哭

**Comment by CMBill** [comment]
好像是这个地方使用了 `bot.sendPrivateMessage` 的缘故

https://github.com/GithubCin/gscore-adapter/blob/04773a621aa23d674ffc3eb7662631143663919c/src/client.ts#L45-L62

koishi 关于 [`bot.sendPrivateMessage` 的文档](https://koishi.chat/zh-CN/api/resources/message.html#bot-sendmessage-%E5%86%85%E7%BD%AE) 里也提到了：

> 只要你能够获取到会话对象，你就不应使用此 API，而应该使用 [`session.send()`](https://koishi.chat/zh-CN/api/core/session.html#session-send)。一些平台会将主动发送的消息同被动接收后回复的消息区分开来，甚至可能限制主动消息的发送，因此使用 [`session.send()`](https://koishi.chat/zh-CN/api/core/session.html#session-send) 总是有更好的可靠性。

似乎使用 `bot.sendPrivateMessage` 发送消息，导致其被视为了主动消息。希望可以修复一下哇

**Comment by GithubCin** [comment]
升级到1.0.27版本，把passive项开到true试试
